version: "3"
services: 
    nginx:
        build: ./nginx
        links: 
            - app1:app1
           
        ports:
            - "80:80"
        networks: 
            - crm-api
    
    app1:
        # restart: always
        build: ./crm
        volumes: 
            - /app/node_modules
            - ./crm:/app
        ports:
            - 5000:5000
        links: 
            - db
        depends_on: 
            - db
        environment: 
            PORT: 5000
            NODE_ENV: production
            
           
        networks: 
            - crm-api

    
    

    db:
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=crm
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mysecretpassword
        ports:
            - "5432:5432"
        restart: unless-stopped

        networks: 
            - crm-api
  
networks: 
    crm-api:
        driver: bridge

volumes: 
    postgres-data:
        driver: local